// <auto-generated>  This file is generated by CmsModelsGenerator. Do not edit manually. </auto-generated>
namespace Constants
{
    public static class Models
    {

        // --- Ungrouped ---
        public const string Bat = "CMS/Bat";
        public const string Bullet = "CMS/Bullet";
        public const string EnemyView = "CMS/View/EnemyView";
        public const string Pistol = "CMS/Pistol";
        public const string Player = "CMS/Player";
        public const string RewardView = "CMS/Buff/RewardView";
        public const string Wave01 = "CMS/Wave01";
        public const string Zombie = "CMS/Zombie";
    }
}
